@startuml
skinparam BoxPadding 15
skinparam ParticipantPadding 15


participant "DID Controller" as DCR
participant "New DID Controller" as NDCR
box "Ardor Blockchain" #WhiteSmoke
    participant "Account" as ATTE
    participant "New Account\n(ARDOR-\n1111-1111-1111-11111)" as NATTE
end box


== Precondition ==

NDCR -> NDCR: create Ardor account
|||


== DID Controller Update ==

DCR -> ATTE: self-update attestation
note right
    accountProperty: {
        pproperty: did://<did id>,
        value: 001|d|1111-1111-1111-11111|c|<txh_s>
    }
end note
NDCR -> NATTE: self-attest new account
note right
    accountProperty: {
        property: did://<did id>,
        value: 001|a|0000-0000-0000-00000|c|<txh_s>
    }
end note


@enduml