@startuml
skinparam BoxPadding 15
skinparam ParticipantPadding 15


participant "Requester" as REQ
participant "DID Resolver" as RES
box "ARDOR Blockchain" #WhiteSmoke
    participant "Account" as ATTE
    participant "New Account" as NATTE
    participant "Tx Resolver" as TXR
    participant "Cloud Storage" as STR
end box



REQ -> RES: request DID resolution\n(did:bba:<txh_d>)
|||


== DID Attestation Parsing ==

loop
    alt is first iteration
        RES -> TXR: get transaction (txh_d)
        RES -> RES: check if transaction is\n DID attestation
    else
        ' RES -> RES: store account name
        RES -> NATTE: get initial DID attestation
        RES -> RES: treat new account\nas current account
    end

    RES -> RES: check if DID attestation is active
    RES -> ATTE: get newer \nDID attestations

    loop over found DID attestations
        RES -> RES: treat found DID attestation\nas current DID attestation
        alt is DID attestation deprecated
            RES -> RES: break loop
        else is DID attestation deactivated
            RES -> RES: stop DID resolution
        end
    end
    alt is DID attestation active
        RES -> RES: break loop
    end
end
|||


== DID Document Template Retrieval\n(Ardor Cloud Storage) ==

RES -> RES: extract cloud storage tx hash (txh_s)
RES -> STR: get DID Document Template (txh_s)
RES -> RES: check if DID Document Template is self-set\n(by one of the found DID controllers)
|||


== DID Document Preparation ==

RES -> RES: add DID informations to the\nDID Document Template
RES -> REQ: return DID Document


@enduml