@startuml
skinparam BoxPadding 15
skinparam ParticipantPadding 15


participant "DID Controller" as DCR
box "Ardor Blockchain" #WhiteSmoke
    participant "Account" as ATTE
    participant "Cloud Storage" as STR
end box


== Precondition ==

DCR -> DCR: create Ardor account
note right
    Ardor account is master key.
    Sub keys are used in DID Document
end note
DCR -> DCR: create DID Document Template


== DID Document Template Storing\n(Ardor Cloud Storage) ==

DCR -> STR: store DID Document Template
STR --> DCR: return transaction hash -> txh_s
|||


== DID Registration ==

DCR -> ATTE: create DID attestation
note right
    accountProperty: {
        property: did://<did id>,
        value: 001|a|0000-0000-0000-00000|c|<txh_s>
    }
end note
ATTE --> DCR: return transaction hash -> txh_d
|||
DCR -> DCR: create DID -> did:bba:<txh_d>


@enduml