@startuml
skinparam BoxPadding 15
skinparam ParticipantPadding 15


participant "DID Controller" as USR
participant "DID Resolver" as RES
box "ARDOR Blockchain" #WhiteSmoke
    participant "Account" as ATTE
    participant "Tx Resolver" as TXR
end box


== DID Deactivation ==

USR -> RES: deactivate DID
|||
RES -> TXR: get attestation property (see DID Resolution)
RES -> ATTE: self-deactivate DID
note right
    accountProperty: {
        property: did://<did id>,
        value: 001|i|0000-0000-0000-00000|c|<txh_s>
    }
end note


@enduml